#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-linkchecker
Version  : 10.2.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/7d/82/aa846862d1b7c60654468cf16e7bdeca256b6a179d1d6f3b5ed3f74487ec/LinkChecker-10.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/7d/82/aa846862d1b7c60654468cf16e7bdeca256b6a179d1d6f3b5ed3f74487ec/LinkChecker-10.2.1.tar.gz
Summary  : check links in web documents or full websites
Group    : Development/Tools
License  : GPL-2.0
Requires: pypi-linkchecker-bin = %{version}-%{release}
Requires: pypi-linkchecker-data = %{version}-%{release}
Requires: pypi-linkchecker-license = %{version}-%{release}
Requires: pypi-linkchecker-man = %{version}-%{release}
Requires: pypi-linkchecker-python = %{version}-%{release}
Requires: pypi-linkchecker-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(argcomplete)
BuildRequires : pypi(beautifulsoup4)
BuildRequires : pypi(dnspython)
BuildRequires : pypi(hatch_vcs)
BuildRequires : pypi(hatchling)
BuildRequires : pypi(pdfminer.six)
BuildRequires : pypi(py)
BuildRequires : pypi(requests)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
For the HTML files in the lconline directory to work, your web server
must have mod_negotiation enabled.
Or you can just remove the .XY suffixes from the language-specific files.

%package bin
Summary: bin components for the pypi-linkchecker package.
Group: Binaries
Requires: pypi-linkchecker-data = %{version}-%{release}
Requires: pypi-linkchecker-license = %{version}-%{release}

%description bin
bin components for the pypi-linkchecker package.


%package data
Summary: data components for the pypi-linkchecker package.
Group: Data

%description data
data components for the pypi-linkchecker package.


%package license
Summary: license components for the pypi-linkchecker package.
Group: Default

%description license
license components for the pypi-linkchecker package.


%package man
Summary: man components for the pypi-linkchecker package.
Group: Default

%description man
man components for the pypi-linkchecker package.


%package python
Summary: python components for the pypi-linkchecker package.
Group: Default
Requires: pypi-linkchecker-python3 = %{version}-%{release}

%description python
python components for the pypi-linkchecker package.


%package python3
Summary: python3 components for the pypi-linkchecker package.
Group: Default
Requires: python3-core
Provides: pypi(linkchecker)
Requires: pypi(argcomplete)
Requires: pypi(beautifulsoup4)
Requires: pypi(dnspython)
Requires: pypi(pdfminer.six)
Requires: pypi(requests)

%description python3
python3 components for the pypi-linkchecker package.


%prep
%setup -q -n linkchecker-10.2.1
cd %{_builddir}/linkchecker-10.2.1
pushd ..
cp -a linkchecker-10.2.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1688015032
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-linkchecker
cp %{_builddir}/linkchecker-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pypi-linkchecker/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/linkchecker

%files data
%defattr(-,root,root,-)
/usr/share/linkchecker/examples/cgi-bin/lc.wsgi
/usr/share/linkchecker/examples/cgi-bin/lconline/check.js
/usr/share/linkchecker/examples/cgi-bin/lconline/index.html
/usr/share/linkchecker/examples/cgi-bin/lconline/lc_cgi.html.de
/usr/share/linkchecker/examples/cgi-bin/lconline/lc_cgi.html.en
/usr/share/linkchecker/examples/cgi-bin/lconline/leer.html.de
/usr/share/linkchecker/examples/cgi-bin/lconline/leer.html.en
/usr/share/linkchecker/examples/check_failures.sh
/usr/share/linkchecker/examples/check_for_x_errors.sh
/usr/share/linkchecker/examples/check_urls.sh
/usr/share/linkchecker/examples/config/create.sql
/usr/share/linkchecker/examples/config/linkchecker-completion
/usr/share/linkchecker/examples/config/linkchecker.apache2.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-linkchecker/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/de/man1/linkchecker.1
/usr/share/man/de/man5/linkcheckerrc.5
/usr/share/man/man1/linkchecker.1
/usr/share/man/man5/linkcheckerrc.5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
