#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v3
# autospec commit: c1050fe
#
Name     : pypi-linkchecker
Version  : 10.4.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/d2/ff/f2a00bf17165fc470d6d02eb191002902a40483a29b474672421f3bd637e/LinkChecker-10.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/d2/ff/f2a00bf17165fc470d6d02eb191002902a40483a29b474672421f3bd637e/LinkChecker-10.4.0.tar.gz
Summary  : check links in web documents or full websites
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 LGPL-3.0
Requires: pypi-linkchecker-bin = %{version}-%{release}
Requires: pypi-linkchecker-data = %{version}-%{release}
Requires: pypi-linkchecker-license = %{version}-%{release}
Requires: pypi-linkchecker-man = %{version}-%{release}
Requires: pypi-linkchecker-python = %{version}-%{release}
Requires: pypi-linkchecker-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(argcomplete)
BuildRequires : pypi(beautifulsoup4)
BuildRequires : pypi(dnspython)
BuildRequires : pypi(hatch_vcs)
BuildRequires : pypi(hatchling)
BuildRequires : pypi(pdfminer.six)
BuildRequires : pypi(py)
BuildRequires : pypi(requests)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
For the HTML files in the lconline directory to work, your web server
must have mod_negotiation enabled.
Or you can just remove the .XY suffixes from the language-specific files.

%package bin
Summary: bin components for the pypi-linkchecker package.
Group: Binaries
Requires: pypi-linkchecker-data = %{version}-%{release}
Requires: pypi-linkchecker-license = %{version}-%{release}

%description bin
bin components for the pypi-linkchecker package.


%package data
Summary: data components for the pypi-linkchecker package.
Group: Data

%description data
data components for the pypi-linkchecker package.


%package license
Summary: license components for the pypi-linkchecker package.
Group: Default

%description license
license components for the pypi-linkchecker package.


%package man
Summary: man components for the pypi-linkchecker package.
Group: Default

%description man
man components for the pypi-linkchecker package.


%package python
Summary: python components for the pypi-linkchecker package.
Group: Default
Requires: pypi-linkchecker-python3 = %{version}-%{release}

%description python
python components for the pypi-linkchecker package.


%package python3
Summary: python3 components for the pypi-linkchecker package.
Group: Default
Requires: python3-core
Provides: pypi(linkchecker)
Requires: pypi(argcomplete)
Requires: pypi(beautifulsoup4)
Requires: pypi(dnspython)
Requires: pypi(pdfminer.six)
Requires: pypi(requests)

%description python3
python3 components for the pypi-linkchecker package.


%prep
%setup -q -n LinkChecker-10.4.0
cd %{_builddir}/LinkChecker-10.4.0
pushd ..
cp -a LinkChecker-10.4.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702928277
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-linkchecker
cp %{_builddir}/LinkChecker-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pypi-linkchecker/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/LinkChecker-%{version}/doc/src/images/COPYING.images %{buildroot}/usr/share/package-licenses/pypi-linkchecker/d4ca5d36d06f97622e54feed256d8bff1c07db4d || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/linkchecker

%files data
%defattr(-,root,root,-)
/usr/share/linkchecker/examples/cgi-bin/lc.wsgi
/usr/share/linkchecker/examples/cgi-bin/lconline/check.js
/usr/share/linkchecker/examples/cgi-bin/lconline/index.html
/usr/share/linkchecker/examples/cgi-bin/lconline/lc_cgi.html.de
/usr/share/linkchecker/examples/cgi-bin/lconline/lc_cgi.html.en
/usr/share/linkchecker/examples/cgi-bin/lconline/leer.html.de
/usr/share/linkchecker/examples/cgi-bin/lconline/leer.html.en
/usr/share/linkchecker/examples/check_failures.sh
/usr/share/linkchecker/examples/check_for_x_errors.sh
/usr/share/linkchecker/examples/check_urls.sh
/usr/share/linkchecker/examples/config/create.sql
/usr/share/linkchecker/examples/config/linkchecker-completion
/usr/share/linkchecker/examples/config/linkchecker.apache2.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-linkchecker/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/pypi-linkchecker/d4ca5d36d06f97622e54feed256d8bff1c07db4d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/de/man1/linkchecker.1
/usr/share/man/de/man5/linkcheckerrc.5
/usr/share/man/man1/linkchecker.1
/usr/share/man/man5/linkcheckerrc.5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
